from typing import Protocol, runtime_checkable

from app.models.source import Source, SourceCreate, SourceUpdate
from app.models.note import Note, NoteCreate, NoteUpdate
from app.models.summary import Summary, SummaryCreate
from app.models.prompt_template import PromptTemplate, PromptTemplateCreate
from app.models.tag import Tag


@runtime_checkable
class SourceRepository(Protocol):
    def create(self, user_id: str, source: SourceCreate) -> Source: ...
    def get_by_id(self, source_id: str) -> Source | None: ...
    def list_all(self, user_id: str, limit: int = 50, offset: int = 0) -> list[Source]: ...
    def update(self, source_id: str, data: SourceUpdate) -> Source | None: ...
    def delete(self, source_id: str) -> bool: ...
    def count(self, user_id: str) -> int: ...


@runtime_checkable
class NoteRepository(Protocol):
    def create(self, user_id: str, note: NoteCreate) -> Note: ...
    def get_by_id(self, note_id: str) -> Note | None: ...
    def list_by_source(self, source_id: str) -> list[Note]: ...
    def list_all(self, user_id: str, limit: int = 50, offset: int = 0) -> list[Note]: ...
    def update(self, note_id: str, data: NoteUpdate) -> Note | None: ...
    def delete(self, note_id: str) -> bool: ...
    def count(self, user_id: str) -> int: ...
    def recent(self, user_id: str, limit: int = 5) -> list[Note]: ...


@runtime_checkable
class SummaryRepository(Protocol):
    def create(self, user_id: str, summary: SummaryCreate) -> Summary: ...
    def list_by_source(self, source_id: str) -> list[Summary]: ...
    def get_by_id(self, summary_id: str) -> Summary | None: ...
    def delete(self, summary_id: str) -> bool: ...


@runtime_checkable
class PromptTemplateRepository(Protocol):
    def create(self, user_id: str, template: PromptTemplateCreate) -> PromptTemplate: ...
    def list_all(self, user_id: str) -> list[PromptTemplate]: ...
    def get_by_id(self, template_id: str) -> PromptTemplate | None: ...
    def delete(self, template_id: str) -> bool: ...


@runtime_checkable
class TagRepository(Protocol):
    def get_or_create(self, user_id: str, name: str) -> Tag: ...
    def list_all(self, user_id: str) -> list[Tag]: ...
    def tag_item(self, tag_id: str, item_id: str, item_type: str) -> None: ...
    def untag_item(self, tag_id: str, item_id: str, item_type: str) -> None: ...
    def get_tags_for_item(self, item_id: str, item_type: str) -> list[Tag]: ...
    def set_tags(self, user_id: str, item_id: str, item_type: str, tag_names: list[str]) -> list[Tag]: ...
